- name: Deploy service to Cloud Run
  uses: stefda/action-cloud-run@v1.6
  with:
    image: gcr.io/marketcode/gustavodfs/casorio
    service: casorio
    project: marketcode
    region: us-central1
    service key: ${{ secrets.GCLOUD_AUTH }}