# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package 
    - name: build image
      run: docker build -t gcr.io/marketcode/gustavodfs/casorio .
    - name: teste
      env: 
          CASORIO: ${{ secrets.GCLOUD_AUTH }}
      run: echo $CASORIO
    - name: push to gcr
      uses: RafikFarhad/push-to-gcr-github-action@v4
      with:
          push_only: true
          gcloud_service_key: ${{ secrets.GCLOUD_AUTH }}
          registry: gcr.io
          project_id: marketcode
          image_name: gustavodfs/casorio
    
   
      
    
      

    
